# Generated by Django 6.0.2 on 2026-04-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otprecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='institute_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
