# Generated by Django 6.0.3 on 2026-04-28 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_institute_name'),
        ('institutes', '0005_institute_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='institute_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='institutes.institute'),
        ),
    ]
