# Generated by Django 6.0.2 on 2026-04-07 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Batch',
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='course_name',
            new_name='batch_name',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='course',
            new_name='batch',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='batch',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='course',
            new_name='batch',
        ),
    ]
