# Generated by Django 6.0.2 on 2026-04-08 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0003_batch_duration_weeks_batch_end_date'),
        ('students', '0003_institution_student_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='batch.batch'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='batch.batch'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='batch.batch'),
        ),
        migrations.RemoveField(
            model_name='libraryissue',
            name='book',
        ),
        migrations.RemoveField(
            model_name='libraryissue',
            name='student',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='LibraryIssue',
        ),
    ]
