# Generated by Django 6.0.2 on 2026-04-08 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0003_alter_institute_registration_code_delete_teacher'),
        ('students', '0004_alter_student_batch_alter_subject_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='institutes.institute'),
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
