# Generated by Django 6.0.2 on 2026-04-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_institution_delete_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rfid_uid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
