# Generated by Django 6.0.2 on 2026-04-09 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_rfid_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='rfid_uid',
        ),
    ]
