# Generated by Django 6.0.2 on 2026-04-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_student_rfid_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rfid_uid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
