# Generated by Django 6.0.3 on 2026-04-22 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_rfid_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='rfid_uid',
        ),
    ]
