# Generated by Django 6.0.2 on 2026-04-07 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='studentbatch',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='student',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='studentbatch',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='note',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='note',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='student',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentbatch',
            name='student',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentBatch',
        ),
    ]
