# Generated by Django 6.0.2 on 2026-04-07 13:58

import generators.id_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0002_remove_attendancerecord_attendance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='registration_code',
            field=models.CharField(default=generators.id_generator.generate_institution_id, editable=False, max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
