# Generated by Django 6.0.2 on 2026-04-24 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0003_alter_institute_registration_code_delete_teacher'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='features',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institute', to='settings.enablefeatures'),
        ),
        migrations.AddField(
            model_name='institute',
            name='settings_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institute', to='settings.settings'),
        ),
    ]
