# Generated by Django 6.0.3 on 2026-04-22 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='rfid_uid',
        ),
    ]
