# Generated by Django 6.0.2 on 2026-04-07 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='end_date',
        ),
    ]
