# Generated by Django 6.0.2 on 2026-04-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0002_remove_batch_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='duration_weeks',
            field=models.PositiveIntegerField(blank=True, help_text='Optional batch duration in weeks. Leave blank for open-ended batches.', null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
