# Generated by Django 6.0.2 on 2026-04-24 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0003_batch_duration_weeks_batch_end_date'),
        ('institutes', '0004_institute_features_institute_settings_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='institutes.institute'),
        ),
    ]
