import { useState, useEffect, useCallback } from 'react';
import api from '../api/axios';

/* ─── Constants ─────────────────────────────────────── */
// registration_code removed — it is auto-generated by the backend
const EMPTY_INSTITUTE = {
  name: '', contact_email: '', phone: '', address: ''
};

/* ─── Components ────────────────────────────────────── */
function Avatar({ name, size = 38, hueOffset = 0 }) {
  const parts = (name || '  ').split(' ');
  const initials = (parts[0]?.[0] ?? '') + (parts[1]?.[0] ?? '');
  const hue = (((parts[0]?.charCodeAt(0) ?? 65) * 7) + hueOffset) % 360;
  return (
    <div style={{
      width: size, height: size, borderRadius: '40%', flexShrink: 0,
      background: `linear-gradient(135deg, hsl(${hue},70%,80%), hsl(${hue},58%,66%))`,
      boxShadow: `0 0 0 2px hsl(${hue},60%,92%), 0 4px 10px hsl(${hue},50%,60%)44`,
      display: 'flex', alignItems: 'center', justifyContent: 'center',
      fontSize: size * 0.35, fontWeight: 800, color: `hsl(${hue},50%,26%)`, letterSpacing: '-0.5px',
    }}>
      {initials.toUpperCase()}
    </div>
  );
}

function ActionBtn({ icon, onClick, title, danger }) {
  return (
    <button title={title} onClick={onClick} style={{
      width: 32, height: 32, borderRadius: 10, border: 'none', cursor: 'pointer',
      display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 13,
      background: 'transparent', transition: 'all 0.2s ease',
      color: danger ? 'var(--red)' : 'var(--text-3)',
    }}
      onMouseEnter={e => {
        e.currentTarget.style.background = danger ? 'rgba(220,38,38,0.08)' : 'rgba(15,23,42,0.06)';
        e.currentTarget.style.color = danger ? 'var(--red)' : 'var(--text)';
      }}
      onMouseLeave={e => {
        e.currentTarget.style.background = 'transparent';
        e.currentTarget.style.color = danger ? 'var(--red)' : 'var(--text-3)';
      }}>
      {icon}
    </button>
  );
}

function SectionCard({ header, children, compact }) {
  return (
    <div style={{
      background: 'white', border: `1px solid var(--border)`,
      borderRadius: 'var(--radius-lg)', overflow: 'hidden',
      boxShadow: '0 2px 12px rgba(15,23,42,0.03)',
      marginBottom: compact ? 0 : '1.5rem',
    }}>
      {header && header}
      <div>{children}</div>
    </div>
  );
}

function EmptyState({ icon, title, sub }) {
  return (
    <div style={{ padding: '4rem 2rem', textAlign: 'center', color: 'var(--text-3)' }}>
      <div style={{ fontSize: 40, marginBottom: 12 }}>{icon}</div>
      <div style={{ fontSize: 16, fontWeight: 700, color: 'var(--text-2)', marginBottom: 4 }}>{title}</div>
      <div style={{ fontSize: 14 }}>{sub}</div>
    </div>
  );
}

function TableHead({ columns }) {
  return (
    <thead>
      <tr style={{ background: 'var(--surface-2)', borderBottom: '1px solid var(--border)' }}>
        {columns.map(c => (
          <th key={c} style={{
            padding: '0.75rem 1.25rem', fontSize: 11, fontWeight: 700,
            textTransform: 'uppercase', letterSpacing: '0.8px', color: 'var(--text-3)',
            textAlign: 'left', whiteSpace: 'nowrap'
          }}>{c}</th>
        ))}
      </tr>
    </thead>
  );
}


/* ─── Directory Tab (Institutes) ─────────────────────── */
function DirectoryTab({ institutes, loading, showForm, setShowForm, onAdded }) {
  const [form, setForm] = useState(EMPTY_INSTITUTE);
  const [saving, setSaving] = useState(false);
  const [err, setErr] = useState(null);
  const [search, setSearch] = useState('');

  const handleSubmit = async (e) => {
    e.preventDefault();
    setSaving(true); setErr(null);
    try {
      await api.post('/institutes/', form);
      setForm(EMPTY_INSTITUTE);
      setShowForm(false);
      onAdded();
    } catch (er) {
      const data = er.response?.data;
      setErr(data ? Object.values(data).flat().join(' ') : 'Failed to create institute.');
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = async (id) => {
    if (!window.confirm("Delete this institute? This cannot be undone.")) return;
    try {
      await api.delete(`/institutes/${id}/`);
      onAdded();
    } catch {
      alert("Error deleting institute. It might contain active records.");
    }
  };

  const filtered = institutes.filter(i =>
    (i.name || '').toLowerCase().includes(search.toLowerCase()) ||
    (i.registration_code || '').toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div style={{ display: 'flex', alignItems: 'flex-start', gap: '2rem' }}>
      {/* List Area */}
      <div style={{ flex: 1, minWidth: 0 }}>
        {/* Toolbar */}
        <div style={{ display: 'flex', gap: 12, marginBottom: '1.5rem', alignItems: 'center' }}>
          <div style={{ position: 'relative', flex: 1, maxWidth: 360 }}>
            <span style={{ position: 'absolute', left: 14, top: 11, color: 'var(--text-3)' }}>🔍</span>
            <input
              type="text"
              placeholder="Search institutes by name or reg code..."
              value={search} onChange={e => setSearch(e.target.value)}
              className="form-input" style={{ paddingLeft: 42, background: 'var(--surface-2)', border: 'none' }}
            />
          </div>
        </div>

        {/* Dynamic Table */}
        <SectionCard compact>
          {loading ? (
            <div style={{ padding: '3rem', textAlign: 'center', color: 'var(--text-3)' }}>
              <div className="spinner" style={{ width: 30, height: 30, margin: '0 auto 1rem' }} />
              Loading institutes catalog...
            </div>
          ) : filtered.length === 0 ? (
            <EmptyState icon="🏢" title={search ? "No matches found" : "Directory is empty"} sub="Adjust your search or register a new institute." />
          ) : (
            <div style={{ overflowX: 'auto' }}>
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
                <TableHead columns={['Institute', 'Contact', 'Reg Code', 'Actions']} />
                <tbody>
                  {filtered.map(i => (
                    <tr key={i.id} style={{ borderBottom: '1px solid var(--border)', transition: 'background 0.15s ease' }}
                      onMouseEnter={e => e.currentTarget.style.background = 'rgba(27,78,140,0.015)'}
                      onMouseLeave={e => e.currentTarget.style.background = 'transparent'}>

                      {/* Institute */}
                      <td style={{ padding: '0.9rem 1.25rem' }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: 14 }}>
                          <Avatar name={i.name} hueOffset={40} />
                          <div>
                            <div style={{ fontWeight: 700, color: 'var(--text)', marginBottom: 2 }}>{i.name}</div>
                            <div style={{ fontSize: 12, color: 'var(--text-3)' }}>{i.address || 'No address provided'}</div>
                          </div>
                        </div>
                      </td>

                      {/* Contact */}
                      <td style={{ padding: '0.9rem 1.25rem' }}>
                        <div style={{ color: 'var(--text-2)', fontSize: 13, marginBottom: 2, display: 'flex', alignItems: 'center', gap: 5 }}>
                          <span style={{ fontSize: 12 }}>📧</span> {i.contact_email}
                        </div>
                        {i.phone && (
                          <div style={{ color: 'var(--text-3)', fontSize: 12, display: 'flex', alignItems: 'center', gap: 5 }}>
                            <span style={{ fontSize: 11 }}>📞</span> {i.phone}
                          </div>
                        )}
                      </td>

                      {/* Reg Code */}
                      <td style={{ padding: '0.9rem 1.25rem' }}>
                        <span style={{
                          fontFamily: 'monospace', fontSize: 12, padding: '3px 10px',
                          borderRadius: 6, background: 'rgba(27,78,140,0.07)',
                          color: 'var(--blue)', fontWeight: 700, letterSpacing: '0.5px',
                        }}>{i.registration_code}</span>
                      </td>

                      {/* Actions */}
                      <td style={{ padding: '0.9rem 1.25rem', textAlign: 'left' }}>
                        <ActionBtn icon="🗑️" title="Delete" danger onClick={() => handleDelete(i.id)} />
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </SectionCard>
      </div>

      {/* Add Form Panel */}
      {showForm && (
        <div style={{
          width: 340, flexShrink: 0, background: 'white',
          border: '1px solid var(--border)', borderRadius: 'var(--radius-lg)',
          padding: '1.5rem', boxShadow: '0 8px 32px rgba(15,23,42,0.08)',
        }}>
          <div style={{ marginBottom: '1.25rem' }}>
            <div style={{ fontWeight: 700, fontSize: 15, color: 'var(--text)', marginBottom: 4 }}>Register New Institute</div>
            <div style={{ fontSize: 13, color: 'var(--text-3)' }}>A unique registration code will be auto-assigned.</div>
          </div>

          {err && (
            <div style={{
              background: 'rgba(220,38,38,0.06)', border: '1px solid rgba(220,38,38,0.2)',
              color: 'var(--red)', borderRadius: 10, padding: '0.75rem 1rem', fontSize: 13, marginBottom: '1rem'
            }}>{err}</div>
          )}

          <form onSubmit={handleSubmit}>
            <div className="form-group">
              <label className="form-label">Institute Name</label>
              <input required className="form-input" placeholder="e.g. Greenwood Academy"
                value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} />
            </div>

            <div className="form-group">
              <label className="form-label">Contact Email</label>
              <input required type="email" className="form-input" placeholder="admin@school.com"
                value={form.contact_email} onChange={e => setForm({ ...form, contact_email: e.target.value })} />
            </div>

            <div className="form-group">
              <label className="form-label">Phone Number</label>
              <input required className="form-input" placeholder="+123..."
                value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} />
            </div>

            <div className="form-group">
              <label className="form-label">Address</label>
              <textarea className="form-input" rows="3" placeholder="Full address"
                value={form.address} onChange={e => setForm({ ...form, address: e.target.value })} />
            </div>

            <div className="divider" style={{ margin: '1.5rem 0' }} />

            <div style={{ display: 'flex', gap: '0.75rem' }}>
              <button type="submit" className="btn btn-primary" disabled={saving} style={{ flex: 1, justifyContent: 'center' }}>
                {saving ? <><span className="spinner" /> Registering…</> : 'Confirm Registration'}
              </button>
            </div>
          </form>
        </div>
      )}
    </div>
  );
}

/* ─── Main Institutes Hub ────────────────────────────── */
export default function InstitutesHub() {
  const [institutes, setInstitutes] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showForm, setShowForm] = useState(false);

  const fetchInst = useCallback((showLoader = false) => {
    if (showLoader) setLoading(true);
    api.get('/institutes/')
      .then(r => setInstitutes(r.data.results || r.data))
      .catch(() => { })
      .finally(() => setLoading(false));
  }, []);

  // eslint-disable-next-line
  useEffect(() => { fetchInst(); }, [fetchInst]);

  return (
    <div className="page-content animate-in">

      {/* ── Hero Header ── */}
      <div style={{
        background: 'linear-gradient(135deg, rgba(27,78,140,0.06) 0%, rgba(124,58,237,0.04) 100%)',
        border: '1px solid var(--border)', borderRadius: 'var(--radius-xl)',
        padding: '1.75rem 2rem', marginBottom: '1.75rem',
        display: 'flex', justifyContent: 'space-between', alignItems: 'center',
        boxShadow: '0 4px 24px rgba(27,78,140,0.06)',
        position: 'relative', overflow: 'hidden',
      }}>
        {/* Decorative blobs */}
        <div style={{ position: 'absolute', top: -30, right: 120, width: 150, height: 150, borderRadius: '50%', background: 'rgba(27,78,140,0.05)', pointerEvents: 'none' }} />
        <div style={{ position: 'absolute', bottom: -20, right: 40, width: 100, height: 100, borderRadius: '50%', background: 'rgba(124,58,237,0.06)', pointerEvents: 'none' }} />

        <div style={{ display: 'flex', alignItems: 'center', gap: 16, zIndex: 1 }}>
          <div style={{
            width: 52, height: 52, borderRadius: 15,
            background: 'linear-gradient(135deg, var(--blue) 0%, #3B82F6 100%)',
            display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 32,
            boxShadow: '0 8px 24px rgba(27,78,140,0.3)',
          }}>🏫</div>
          <div>
            <h1 className="page-title" style={{ marginBottom: 2 }}>Institutes Database</h1>
            <p className="page-subtitle" style={{ margin: 0 }}>
              {loading ? 'Syncing...' : `${institutes.length} organizations onboarded`}
            </p>
          </div>
        </div>

        <button className="btn btn-primary" style={{
          zIndex: 1, background: 'linear-gradient(135deg, var(--blue), #3B82F6)',
          boxShadow: '0 4px 16px rgba(27,78,140,0.3)', fontSize: 13,
          display: 'flex', alignItems: 'center', gap: 6,
        }} onClick={() => setShowForm(f => !f)}>
          {showForm ? '✕ Cancel' : '+ Add Institute'}
        </button>
      </div>

      {/* ── Tab Content ── */}
      <div className="card card-p animate-in"
        style={{ boxShadow: '0 4px 20px rgba(15,23,42,0.05)', padding: '1.5rem' }}>
        <DirectoryTab
          institutes={institutes} loading={loading}
          showForm={showForm} setShowForm={setShowForm}
          onAdded={fetchInst}
        />
      </div>
    </div>
  );
}